### ISSUE TITLE
Fatal error, directory public does not exist

### ISSUE THREAD

**Issue by Seda145** [bolt/project#113]
After uploading the website to the server, Bolt does not handle the public folder properly which was "public" on the local machine and is "public_html" on the server. clearing cache makes no difference. What am I looking at?

Backend fatal error: PHP Fatal error:  Uncaught Exception: The directory "/home/*/domains/website.com/public/theme/ThemeName" does not exist. in /home/*/domains/website.com/vendor/php-translation/symfony-bundle/DependencyInjection/Configuration.php:131\nStack trace:\n#0 /home/*/domains/website.com/vendor/symfony/config/Definition/Builder/ExprBuilder.php(239): Translation\\Bundle\\DependencyInjection\\Configuration->Translation\\Bundle\\DependencyInjection\\{closure}('/home/*...')\n#1 /home/*/domains/website.com/vendor/symfony/config/Definition/BaseNode.php(461): Symfony\\Component\\Config\\Definition\\Builder\\ExprBuilder::Symfony\\Component\\Config\\Definition\\Builder\\{closure}('/home/*...')\n#2 /home/*/domains/website.com/vendor/symfony/config/Definition/PrototypedArrayNode.php(177): Symfony\\Component\\Config\\Definition\\BaseNode->finalize('/home/*...')\n#3 /home/*/domains/website.com/vendor/symfony/config/Definition/BaseNo in /home/*/domains/website.com/vendor/symfony/config/Definition/BaseNode.php on line 469\n

**Comment by Seda145** [comment]
Actually, it doesn't even work right after installing bolt through composer, if you change the directory name right after bolt:setup to "public_html", you get this:

In BaseNode.php line 469:
Invalid configuration for path "translation.configs.site.dirs.0": The directory "K:/publictestwebsite/public/theme/base-2021" does not exist.

In Configuration.php line 131:
The directory "K:/publictestwebsite/public/theme/base-2021" does not exist.

Isn't Kernel::getPublicFolder() supposed to handle this?

**Comment by bobdenotter** [comment]
I don't think that's supported currently. It'd be a nice feature, if we could add support for that, though.

**Comment by Seda145** [comment]
Ah ok, after scanning the source I thought I ran into some kind of bug at first because there does seem to be a partial implementation of this in Bolt. The public folder's name is even stored in the cache. In the end I used a symbolic link to keep both Bolt and the server happy with the name of the public folder.
